[package]
name = "parallel-playground"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
bytemuck = "1.7.2"
env_logger = "0.9.0"
pollster = "0.2.4"
wgpu = { version = "0.10.1", features = ["spirv"] }
