#version 450

layout(set = 0, binding = 0) writeonly buffer Output {
    uint output_buffer[];
};

layout(set = 0, binding = 0) readonly buffer Indices {
    uint indices_buffer[];
};

layout(push_constant) uniform PushConstants {
    uint value;
};

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

void main() {
    uint i = gl_GlobalInvocationID.x;

    if (i >= indices_buffer.length()) {
        return;
    }

    output_buffer[indices_buffer[i]] = value;
}
